# Generated by Django 6.0.4 on 2026-05-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
